/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include "BrowserTypes.hpp"


namespace v1_0 {
namespace org {
namespace genivi {
namespace mediamanager {


bool BrowserTypes::SortKey::operator==(const BrowserTypes::SortKey& _other) const {
	return (getOrder() == _other.getOrder() && getKeyName() == _other.getKeyName());
}


} // namespace mediamanager
} // namespace genivi
} // namespace org
} // namespace v1_0
