/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef COMMONAPI_DBUS_INDEXER_DEPLOYMENT_HPP_
#define COMMONAPI_DBUS_INDEXER_DEPLOYMENT_HPP_

#include <v1_0/org/genivi/mediamanager/MediaTypesDBusDeployment.hpp>
#include <v1_0/org/genivi/mediamanager/IndexerDBusDeployment.hpp>        

#include <v1_0/org/genivi/mediamanager/IndexerDBusDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/DBus/DBusDeployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1_0 {
namespace org {
namespace genivi {
namespace mediamanager {
namespace Indexer_ {

// Interface-specific deployment types
typedef CommonAPI::EmptyDeployment IndexerErrorDeployment_t;


// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployments

// Broadcast-specific deployments


} // namespace Indexer_
} // namespace mediamanager
} // namespace genivi
} // namespace org
} // namespace v1_0

#endif // COMMONAPI_DBUS_INDEXER_DEPLOYMENT_HPP_
