/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/**
 * description: Indexer control interface. Allows administerial tasks for
                  the
 *   indexer backend, such as starting, stopping and requesting
                 
 *   status of the indexer.
                  For querying the database, please
 *   see
                  org.genivi.mediamanager.Browser
 */
#include "Indexer.hpp"

namespace v1_0 {
namespace org {
namespace genivi {
namespace mediamanager {


/**
 * description: RUNNING: The indexer is currently traversing files and/or
                     
 *            extracting metadata
                      STOPPED: The indexer has
 *   been stopped and will not start
                                 indexing by
 *   itself
                      IDLE:    The indexer has finished, and is waiting
 *   for new
                                 files to index
 */

} // namespace mediamanager
} // namespace genivi
} // namespace org
} // namespace v1_0
