/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef ORG_GENIVI_MEDIAMANAGER_PLAYER_TYPES_DBUS_DEPLOYMENT_HPP_
#define ORG_GENIVI_MEDIAMANAGER_PLAYER_TYPES_DBUS_DEPLOYMENT_HPP_

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/DBus/DBusDeployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1_0 {
namespace org {
namespace genivi {
namespace mediamanager {
namespace PlayerTypes_ {

// typecollection-specific deployment types
typedef CommonAPI::EmptyDeployment MuteStatusDeployment_t;

typedef CommonAPI::EmptyDeployment PlayerErrorDeployment_t;

typedef CommonAPI::EmptyDeployment ShuffleStatusDeployment_t;

typedef CommonAPI::EmptyDeployment RepeatStatusDeployment_t;

typedef CommonAPI::EmptyDeployment PlaybackStatusDeployment_t;


// typecollection-specific deployments

} // namespace PlayerTypes_
} // namespace mediamanager
} // namespace genivi
} // namespace org
} // namespace v1_0

#endif // ORG_GENIVI_MEDIAMANAGER_PLAYER_TYPES_DBUS_DEPLOYMENT_HPP_
